### ISSUE TITLE
App crashes when clicking on annotation

### ISSUE THREAD

**Issue by svetlana-bilevich** [epam/badgerdoc#427] opened 2023-03-14 10:56 UTC
Open http://dev1.badgerdoc.com/documents/1003?jobId=2006&revisionId=31ea7273830cb537ca0bb08ffc56f7a0b449cceb
click on first annotation

**Comment by khyurri** [comment] 2023-03-14 13:35
Possible duplicate of #428

**Closed** 2023-03-15 13:44 UTC
Labels: bug
